name: kron

services:
  nginx:
    container_name: kron_nginx
    image: nginx:stable-alpine3.23-perl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - frontend
      - backend
  frontend:
    container_name: kron_frontend
    image: oven/bun:alpine
    working_dir: /app
    command: sh -c "bun install && bun run dev --host"
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=https://kron.winnerx0.dev/api
    networks:
      - backend
  backend:
    container_name: kron_backend
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_NAME=kron
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
  db:
    container_name: kron_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kron
    volumes:
      - kron_db:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kron"]
      interval: 10s
      timeout: 5s
      retries: 5
  certbot:
    container_name: kron_certbot
    image: certbot/certbot:latest
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done"
    volumes:
      - nginx_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - frontend
networks:
  frontend:
  backend:

volumes:
  kron_db:
  nginx_logs:
  nginx_certs:
    external: true
  certbot_www:
